/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc4380;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author aaron
 */
public class View extends javax.swing.JFrame {

    Controller controller;
    
    int lastScore;
    
    String currentVehicle;
    
    /**
     * Creates new form View
     */
    public View(Controller c) {
        controller = c;
        initComponents();
        setVisible(true);
        lastScore = 0;
        // Here we need to set the default value of currentVehicle. currentVehicle = "";

    }

    public void setLastScore(int s)
    {
        lastScore = s;
    }
    public void changeContext(String con)
    {
        //This code will change the card displayed from the game panel to 
        //panel represented by the passed in string
    }
    
    //This method returns the string that represents the current color of the selected
    //vehicle
    public String getCurrentVehicle() {
      return currentVehicle;  
    }
    
    public void setCurrentVehicle(String c)
    {
        currentVehicle = c;
    }
    public int getMoney()
    {
        return controller.getMoney();
    }
    public void setMoney(int m)
    {
        controller.setMoney(m);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
